version: '3.8'

services:
  db:
    image: postgres:13
    ports:
       - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./seeds/init.sql.example:/docker-entrypoint-initdb.d/init.sql
    restart: always
  grpc-server:
    build: .
    env_file:
      - .env
    ports:
      - "8090:8090"
    restart: always
volumes:
  db_data:
