name: Audit

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Bazel setup
        run: bazelisk run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //:gazelle

      - name: Update Gazelle with Bazel
        run: bazelisk run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //:gazelle -- update;

      - name: Update dependencies with Bazel
        run: bazelisk run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //:gazelle -- update-repos -from_file=go.mod;

      - name: Run tests with Bazel
        run: bazelisk test \
          --action_env=DB_TYPE=$(DB_TYPE) \
          --action_env=DB_USERNAME=$(DB_USERNAME) \
          --action_env=DB_PASSWORD=$(DB_PASSWORD) \
          --action_env=DB_HOSTNAME=$(DB_HOSTNAME) \
          --action_env=DB_PORT=$(DB_PORT) \
          --action_env=POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
          --action_env=SERVER_HOST=$(SERVER_HOST) \
          --action_env=GRPC_SERVER_PORT=$(GRPC_SERVER_PORT) \
          --action_env=GRPC_GATEWAY_SERVER_PORT=$(GRPC_GATEWAY_SERVER_PORT) \
          --platform_suffix="bazel-test" \
          --@io_bazel_rules_go//go/config:race \
          --define cluster=$CLUSTER \
          --define namespace=$NAMESPACE \
          --test_tag_filters=fast \
          --build_tag_filters=fast \
          --test_output=errors \
          --nocache_test_results \
          //...

      - name: Clean bazel
        run: bazelisk clean