name: Audit

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Bazel setup
        run: make bazel-setup

      - name: Update dependencies with Bazel
        run: make bazel-update-deps

      - name: Run tests with Bazel
        run:  make bazel-test

      - name: Clean bazel
        run: make bazel-clean